### ISSUE TITLE
Install issues on Mac OS X 10.6.6 and MacPorts 1.9.2

### ISSUE THREAD

**Issue by thorsten** [peritus/geocommit#3] opened 2011-01-10 16:17 UTC
Downloading/unpacking geocommit
  Getting page http://pypi.python.org/simple/geocommit
  URLs to search for versions for geocommit:
- http://pypi.python.org/simple/geocommit/
  Getting page http://pypi.python.org/geocommit
  Could not fetch URL http://pypi.python.org/geocommit (from http://pypi.python.org/simple/geocommit/): HTTP Error 404: Not Found
  Will skip URL http://pypi.python.org/geocommit when looking for download links for geocommit
  Analyzing links from page http://pypi.python.org/simple/geocommit/
    Found link http://pypi.python.org/packages/source/g/geocommit/geocommit-0.9.0b2.tar.gz#md5=940fcfd535fda2de47692cb37d9fb664 (from http://pypi.python.org/simple/geocommit/), version: 0.9.0b2
    Found link http://pypi.python.org/packages/2.6/g/geocommit/geocommit-0.9.0b1.macosx-10.6-universal.tar.gz#md5=11a16b3886e69ce5e4a80c0a5bab8225 (from http://pypi.python.org/simple/geocommit/), version: 0.9.0b1.macosx-10.6-universal
    Found link http://pypi.python.org/packages/source/g/geocommit/geocommit-0.9.0b1.tar.gz#md5=884925f3c9a6d8da761ffb6c70c8e777 (from http://pypi.python.org/simple/geocommit/), version: 0.9.0b1
    Found link http://pypi.python.org/packages/source/g/geocommit/geocommit-0.9.2.tar.gz#md5=ca7afac17c75de0fb513f40c9b84ea8b (from http://pypi.python.org/simple/geocommit/), version: 0.9.2
    Found link http://pypi.python.org/packages/source/g/geocommit/geocommit-0.9.1.tar.gz#md5=ca593de75333a4fbf1cf71c83f80ec4e (from http://pypi.python.org/simple/geocommit/), version: 0.9.1
    Found link http://pypi.python.org/packages/source/g/geocommit/geocommit-0.9.1b1.tar.gz#md5=000917b44ade7f432b4d4dfd7e2a0e6e (from http://pypi.python.org/simple/geocommit/), version: 0.9.1b1
    Skipping link http://pypi.python.org/geocommit (from http://pypi.python.org/simple/geocommit/); not a file
  Using version 0.9.2 (newest of versions: 0.9.2, 0.9.1, 0.9.1b1, 0.9.0b2, 0.9.0b1.macosx-10.6-universal, 0.9.0b1)
  Downloading geocommit-0.9.2.tar.gz
  Downloading from URL http://pypi.python.org/packages/source/g/geocommit/geocommit-0.9.2.tar.gz#md5=ca7afac17c75de0fb513f40c9b84ea8b (from http://pypi.python.org/simple/geocommit/)
  Running setup.py egg_info for package geocommit
    running egg_info
    creating pip-egg-info/geocommit.egg-info
    writing requirements to pip-egg-info/geocommit.egg-info/requires.txt
    writing pip-egg-info/geocommit.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/geocommit.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/geocommit.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/geocommit.egg-info/entry_points.txt
    writing manifest file 'pip-egg-info/geocommit.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    reading manifest file 'pip-egg-info/geocommit.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/geocommit.egg-info/SOURCES.txt'
  Installing collected packages: geocommit
  Running setup.py install for geocommit
    Running command /opt/local/Library/Frameworks/Python.framework/Versions/2.6/Resources/Python.app/Contents/MacOS/Python -c "import setuptools; **file**='/Users/thorsten/build/geocommit/setup.py'; execfile('/Users/thorsten/build/geocommit/setup.py')" install --single-version-externally-managed --record /tmp/pip-zGqty0-record/install-record.txt
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-x86_64-2.6
    creating build/lib.macosx-10.6-x86_64-2.6/geocommit
    copying src/geocommit/**init**.py -> build/lib.macosx-10.6-x86_64-2.6/geocommit
    copying src/geocommit/location.py -> build/lib.macosx-10.6-x86_64-2.6/geocommit
    copying src/geocommit/locationprovider.py -> build/lib.macosx-10.6-x86_64-2.6/geocommit
    copying src/geocommit/networkmanager.py -> build/lib.macosx-10.6-x86_64-2.6/geocommit
    copying src/geocommit/tests.py -> build/lib.macosx-10.6-x86_64-2.6/geocommit
    copying src/geocommit/util.py -> build/lib.macosx-10.6-x86_64-2.6/geocommit
    copying src/geocommit/wifilocationprovider.py -> build/lib.macosx-10.6-x86_64-2.6/geocommit
    creating build/lib.macosx-10.6-x86_64-2.6/geocommit/provider
    copying src/geocommit/provider/**init**.py -> build/lib.macosx-10.6-x86_64-2.6/geocommit/provider
    creating build/lib.macosx-10.6-x86_64-2.6/geocommit/provider/corelocation
    copying src/geocommit/provider/corelocation/**init**.py -> build/lib.macosx-10.6-x86_64-2.6/geocommit/provider/corelocation
    running build_ext
    building 'geocommit.provider.corelocation.geocommit' extension
    creating build/temp.macosx-10.6-x86_64-2.6
    creating build/temp.macosx-10.6-x86_64-2.6/src
    creating build/temp.macosx-10.6-x86_64-2.6/src/geocommit
    creating build/temp.macosx-10.6-x86_64-2.6/src/geocommit/provider
    creating build/temp.macosx-10.6-x86_64-2.6/src/geocommit/provider/corelocation
    /usr/bin/gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -pipe -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.6/include/python2.6 -c src/geocommit/provider/corelocation/geocommit.m -o build/temp.macosx-10.6-x86_64-2.6/src/geocommit/provider/corelocation/geocommit.o
    src/geocommit/provider/corelocation/geocommit.m:1:34: error: Foundation/foundation.h: No such file or directory
    error: command '/usr/bin/gcc-4.2' failed with exit status 1
    Complete output from command /opt/local/Library/Frameworks/Python.framework/Versions/2.6/Resources/Python.app/Contents/MacOS/Python -c "import setuptools; **file**='/Users/thorsten/build/geocommit/setup.py'; execfile('/Users/thorsten/build/geocommit/setup.py')" install --single-version-externally-managed --record /tmp/pip-zGqty0-record/install-record.txt:
    running install

running build

running build_py

creating build

creating build/lib.macosx-10.6-x86_64-2.6

creating build/lib.macosx-10.6-x86_64-2.6/geocommit

copying src/geocommit/**init**.py -> build/lib.macosx-10.6-x86_64-2.6/geocommit

copying src/geocommit/location.py -> build/lib.macosx-10.6-x86_64-2.6/geocommit

copying src/geocommit/locationprovider.py -> build/lib.macosx-10.6-x86_64-2.6/geocommit

copying src/geocommit/networkmanager.py -> build/lib.macosx-10.6-x86_64-2.6/geocommit

copying src/geocommit/tests.py -> build/lib.macosx-10.6-x86_64-2.6/geocommit

copying src/geocommit/util.py -> build/lib.macosx-10.6-x86_64-2.6/geocommit

copying src/geocommit/wifilocationprovider.py -> build/lib.macosx-10.6-x86_64-2.6/geocommit

creating build/lib.macosx-10.6-x86_64-2.6/geocommit/provider

copying src/geocommit/provider/**init**.py -> build/lib.macosx-10.6-x86_64-2.6/geocommit/provider

creating build/lib.macosx-10.6-x86_64-2.6/geocommit/provider/corelocation

copying src/geocommit/provider/corelocation/**init**.py -> build/lib.macosx-10.6-x86_64-2.6/geocommit/provider/corelocation

running build_ext

building 'geocommit.provider.corelocation.geocommit' extension

creating build/temp.macosx-10.6-x86_64-2.6

creating build/temp.macosx-10.6-x86_64-2.6/src

creating build/temp.macosx-10.6-x86_64-2.6/src/geocommit

creating build/temp.macosx-10.6-x86_64-2.6/src/geocommit/provider

creating build/temp.macosx-10.6-x86_64-2.6/src/geocommit/provider/corelocation

/usr/bin/gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -pipe -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.6/include/python2.6 -c src/geocommit/provider/corelocation/geocommit.m -o build/temp.macosx-10.6-x86_64-2.6/src/geocommit/provider/corelocation/geocommit.o

src/geocommit/provider/corelocation/geocommit.m:1:34: error: Foundation/foundation.h: No such file or directory

error: command '/usr/bin/gcc-4.2' failed with exit status 1

---

Command /opt/local/Library/Frameworks/Python.framework/Versions/2.6/Resources/Python.app/Contents/MacOS/Python -c "import setuptools; **file**='/Users/thorsten/build/geocommit/setup.py'; execfile('/Users/thorsten/build/geocommit/setup.py')" install --single-version-externally-managed --record /tmp/pip-zGqty0-record/install-record.txt failed with error code 1
Exception information:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/pip/basecommand.py", line 120, in main
    self.run(options, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/pip/commands/install.py", line 165, in run
    requirement_set.install(install_options)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/pip/req.py", line 1243, in install
    requirement.install(install_options)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/pip/req.py", line 540, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/pip/__init__.py", line 226, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command /opt/local/Library/Frameworks/Python.framework/Versions/2.6/Resources/Python.app/Contents/MacOS/Python -c "import setuptools; **file**='/Users/thorsten/build/geocommit/setup.py'; execfile('/Users/thorsten/build/geocommit/setup.py')" install --single-version-externally-managed --record /tmp/pip-zGqty0-record/install-record.txt failed with error code 1

**Comment by peritus** [comment] 2011-07-18 19:50
Duplicate of #6, fixed in geocommit 0.9.3beta1, you can upgrade with `pip install --upgrade geocommit`.

**Closed as completed by peritus** 2011-07-18 19:50 UTC
